// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package sender

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1d751f33DecodeVelvetSender(in *jlexer.Lexer, out *SenderConns) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d751f33EncodeVelvetSender(out *jwriter.Writer, in SenderConns) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SenderConns) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1d751f33EncodeVelvetSender(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SenderConns) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1d751f33EncodeVelvetSender(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SenderConns) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1d751f33DecodeVelvetSender(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SenderConns) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1d751f33DecodeVelvetSender(l, v)
}
func easyjson1d751f33DecodeVelvetSender1(in *jlexer.Lexer, out *Sender) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "mtas":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.MTAs = make(map[string]*MTA)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 *MTA
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(MTA)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					(out.MTAs)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "sinkid":
			out.SinkID = string(in.String())
		case "warmups":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Warmups = make(map[string]*Warmup)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 *Warmup
					if in.IsNull() {
						in.Skip()
						v2 = nil
					} else {
						if v2 == nil {
							v2 = new(Warmup)
						}
						easyjson1d751f33DecodeVelvetSender2(in, v2)
					}
					(out.Warmups)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		case "dkim":
			if in.IsNull() {
				in.Skip()
				out.DKIM = nil
			} else {
				if out.DKIM == nil {
					out.DKIM = new(DKIMSettings)
				}
				easyjson1d751f33DecodeVelvetSender3(in, out.DKIM)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d751f33EncodeVelvetSender1(out *jwriter.Writer, in Sender) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"mtas\":"
		out.RawString(prefix[1:])
		if in.MTAs == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v3First := true
			for v3Name, v3Value := range in.MTAs {
				if v3First {
					v3First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v3Name))
				out.RawByte(':')
				if v3Value == nil {
					out.RawString("null")
				} else {
					(*v3Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"sinkid\":"
		out.RawString(prefix)
		out.String(string(in.SinkID))
	}
	{
		const prefix string = ",\"warmups\":"
		out.RawString(prefix)
		if in.Warmups == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.Warmups {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				if v4Value == nil {
					out.RawString("null")
				} else {
					easyjson1d751f33EncodeVelvetSender2(out, *v4Value)
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"dkim\":"
		out.RawString(prefix)
		if in.DKIM == nil {
			out.RawString("null")
		} else {
			easyjson1d751f33EncodeVelvetSender3(out, *in.DKIM)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Sender) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1d751f33EncodeVelvetSender1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Sender) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1d751f33EncodeVelvetSender1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Sender) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1d751f33DecodeVelvetSender1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Sender) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1d751f33DecodeVelvetSender1(l, v)
}
func easyjson1d751f33DecodeVelvetSender3(in *jlexer.Lexer, out *DKIMSettings) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "selector":
			out.Selector = string(in.String())
		case "entries":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Entries = make(map[string]*DKIMEntry)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v5 *DKIMEntry
					if in.IsNull() {
						in.Skip()
						v5 = nil
					} else {
						if v5 == nil {
							v5 = new(DKIMEntry)
						}
						easyjson1d751f33DecodeVelvetSender4(in, v5)
					}
					(out.Entries)[key] = v5
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d751f33EncodeVelvetSender3(out *jwriter.Writer, in DKIMSettings) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"selector\":"
		out.RawString(prefix[1:])
		out.String(string(in.Selector))
	}
	{
		const prefix string = ",\"entries\":"
		out.RawString(prefix)
		if in.Entries == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v6First := true
			for v6Name, v6Value := range in.Entries {
				if v6First {
					v6First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v6Name))
				out.RawByte(':')
				if v6Value == nil {
					out.RawString("null")
				} else {
					easyjson1d751f33EncodeVelvetSender4(out, *v6Value)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}
func easyjson1d751f33DecodeVelvetSender4(in *jlexer.Lexer, out *DKIMEntry) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "private":
			out.Private = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d751f33EncodeVelvetSender4(out *jwriter.Writer, in DKIMEntry) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"private\":"
		out.RawString(prefix[1:])
		out.String(string(in.Private))
	}
	out.RawByte('}')
}
func easyjson1d751f33DecodeVelvetSender2(in *jlexer.Lexer, out *Warmup) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "allips":
			if in.IsNull() {
				in.Skip()
				out.AllIPs = nil
			} else {
				in.Delim('[')
				if out.AllIPs == nil {
					if !in.IsDelim(']') {
						out.AllIPs = make([]string, 0, 4)
					} else {
						out.AllIPs = []string{}
					}
				} else {
					out.AllIPs = (out.AllIPs)[:0]
				}
				for !in.IsDelim(']') {
					var v7 string
					v7 = string(in.String())
					out.AllIPs = append(out.AllIPs, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "domains":
			out.Domains = string(in.String())
		case "excludedomains":
			out.ExcludeDomains = string(in.String())
		case "dailylimit":
			out.DailyLimit = int(in.Int())
		case "rampfactor":
			out.RampFactor = int(in.Int())
		case "threshold":
			out.Threshold = int(in.Int())
		case "thresholddays":
			out.ThresholdDays = int(in.Int())
		case "dayoverrides":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.DayOverrides = make(map[string]int)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v8 int
					v8 = int(in.Int())
					(out.DayOverrides)[key] = v8
					in.WantComma()
				}
				in.Delim('}')
			}
		case "priority":
			out.Priority = string(in.String())
		case "limitcount":
			out.LimitCount = int(in.Int())
		case "afterlimit":
			out.AfterLimit = string(in.String())
		case "disabled":
			out.Disabled = bool(in.Bool())
		case "increments":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Increments = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v9 string
					v9 = string(in.String())
					(out.Increments)[key] = v9
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d751f33EncodeVelvetSender2(out *jwriter.Writer, in Warmup) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"allips\":"
		out.RawString(prefix[1:])
		if in.AllIPs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.AllIPs {
				if v10 > 0 {
					out.RawByte(',')
				}
				out.String(string(v11))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"domains\":"
		out.RawString(prefix)
		out.String(string(in.Domains))
	}
	{
		const prefix string = ",\"excludedomains\":"
		out.RawString(prefix)
		out.String(string(in.ExcludeDomains))
	}
	{
		const prefix string = ",\"dailylimit\":"
		out.RawString(prefix)
		out.Int(int(in.DailyLimit))
	}
	{
		const prefix string = ",\"rampfactor\":"
		out.RawString(prefix)
		out.Int(int(in.RampFactor))
	}
	{
		const prefix string = ",\"threshold\":"
		out.RawString(prefix)
		out.Int(int(in.Threshold))
	}
	{
		const prefix string = ",\"thresholddays\":"
		out.RawString(prefix)
		out.Int(int(in.ThresholdDays))
	}
	{
		const prefix string = ",\"dayoverrides\":"
		out.RawString(prefix)
		if in.DayOverrides == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v12First := true
			for v12Name, v12Value := range in.DayOverrides {
				if v12First {
					v12First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v12Name))
				out.RawByte(':')
				out.Int(int(v12Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"priority\":"
		out.RawString(prefix)
		out.String(string(in.Priority))
	}
	{
		const prefix string = ",\"limitcount\":"
		out.RawString(prefix)
		out.Int(int(in.LimitCount))
	}
	{
		const prefix string = ",\"afterlimit\":"
		out.RawString(prefix)
		out.String(string(in.AfterLimit))
	}
	{
		const prefix string = ",\"disabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.Disabled))
	}
	{
		const prefix string = ",\"increments\":"
		out.RawString(prefix)
		if in.Increments == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v13First := true
			for v13Name, v13Value := range in.Increments {
				if v13First {
					v13First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v13Name))
				out.RawByte(':')
				out.String(string(v13Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}
func easyjson1d751f33DecodeVelvetSender5(in *jlexer.Lexer, out *SendLimits) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "lastcheck":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.LastCheck).UnmarshalJSON(data))
			}
		case "sendcount":
			out.SendCount = int(in.Int())
		case "sendcounthour":
			out.SendCountHour = int(in.Int())
		case "deliveredcount":
			out.DeliveredCount = int(in.Int())
		case "prevdelivered":
			if in.IsNull() {
				in.Skip()
				out.PrevDelivered = nil
			} else {
				in.Delim('[')
				if out.PrevDelivered == nil {
					if !in.IsDelim(']') {
						out.PrevDelivered = make([]int, 0, 8)
					} else {
						out.PrevDelivered = []int{}
					}
				} else {
					out.PrevDelivered = (out.PrevDelivered)[:0]
				}
				for !in.IsDelim(']') {
					var v14 int
					v14 = int(in.Int())
					out.PrevDelivered = append(out.PrevDelivered, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "deliveredcountminute":
			out.DeliveredCountMinute = int(in.Int())
		case "prevdeliveredminutes":
			if in.IsNull() {
				in.Skip()
				out.PrevDeliveredMinutes = nil
			} else {
				in.Delim('[')
				if out.PrevDeliveredMinutes == nil {
					if !in.IsDelim(']') {
						out.PrevDeliveredMinutes = make([]int, 0, 8)
					} else {
						out.PrevDeliveredMinutes = []int{}
					}
				} else {
					out.PrevDeliveredMinutes = (out.PrevDeliveredMinutes)[:0]
				}
				for !in.IsDelim(']') {
					var v15 int
					v15 = int(in.Int())
					out.PrevDeliveredMinutes = append(out.PrevDeliveredMinutes, v15)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "deferuntil":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.DeferUntil).UnmarshalJSON(data))
			}
		case "defererr":
			out.DeferError = bool(in.Bool())
		case "deferrate":
			out.DeferRate = bool(in.Bool())
		case "defermatch":
			out.DeferMatch = string(in.String())
		case "defercount":
			out.DeferCount = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d751f33EncodeVelvetSender5(out *jwriter.Writer, in SendLimits) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"lastcheck\":"
		out.RawString(prefix[1:])
		out.Raw((in.LastCheck).MarshalJSON())
	}
	{
		const prefix string = ",\"sendcount\":"
		out.RawString(prefix)
		out.Int(int(in.SendCount))
	}
	{
		const prefix string = ",\"sendcounthour\":"
		out.RawString(prefix)
		out.Int(int(in.SendCountHour))
	}
	{
		const prefix string = ",\"deliveredcount\":"
		out.RawString(prefix)
		out.Int(int(in.DeliveredCount))
	}
	{
		const prefix string = ",\"prevdelivered\":"
		out.RawString(prefix)
		if in.PrevDelivered == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v16, v17 := range in.PrevDelivered {
				if v16 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v17))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"deliveredcountminute\":"
		out.RawString(prefix)
		out.Int(int(in.DeliveredCountMinute))
	}
	{
		const prefix string = ",\"prevdeliveredminutes\":"
		out.RawString(prefix)
		if in.PrevDeliveredMinutes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.PrevDeliveredMinutes {
				if v18 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v19))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"deferuntil\":"
		out.RawString(prefix)
		out.Raw((in.DeferUntil).MarshalJSON())
	}
	{
		const prefix string = ",\"defererr\":"
		out.RawString(prefix)
		out.Bool(bool(in.DeferError))
	}
	{
		const prefix string = ",\"deferrate\":"
		out.RawString(prefix)
		out.Bool(bool(in.DeferRate))
	}
	{
		const prefix string = ",\"defermatch\":"
		out.RawString(prefix)
		out.String(string(in.DeferMatch))
	}
	{
		const prefix string = ",\"defercount\":"
		out.RawString(prefix)
		out.Int(int(in.DeferCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SendLimits) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1d751f33EncodeVelvetSender5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SendLimits) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1d751f33EncodeVelvetSender5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SendLimits) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1d751f33DecodeVelvetSender5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SendLimits) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1d751f33DecodeVelvetSender5(l, v)
}
func easyjson1d751f33DecodeVelvetSender6(in *jlexer.Lexer, out *MTASettings) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "numconns":
			out.NumConns = int(in.Int())
		case "customnumconns":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.CustomNumConns = make(map[string]int)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v20 int
					v20 = int(in.Int())
					(out.CustomNumConns)[key] = v20
					in.WantComma()
				}
				in.Delim('}')
			}
		case "retryfor":
			out.RetryFor = int(in.Int())
		case "sendsperconn":
			out.SendsPerConn = int(in.Int())
		case "deferwaitsecs":
			if in.IsNull() {
				in.Skip()
				out.DeferWaitSecs = nil
			} else {
				in.Delim('[')
				if out.DeferWaitSecs == nil {
					if !in.IsDelim(']') {
						out.DeferWaitSecs = make([]int, 0, 8)
					} else {
						out.DeferWaitSecs = []int{}
					}
				} else {
					out.DeferWaitSecs = (out.DeferWaitSecs)[:0]
				}
				for !in.IsDelim(']') {
					var v21 int
					v21 = int(in.Int())
					out.DeferWaitSecs = append(out.DeferWaitSecs, v21)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "customwaitsecs":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.CustomWaitSecs = make(map[string][]int)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v22 []int
					if in.IsNull() {
						in.Skip()
						v22 = nil
					} else {
						in.Delim('[')
						if v22 == nil {
							if !in.IsDelim(']') {
								v22 = make([]int, 0, 8)
							} else {
								v22 = []int{}
							}
						} else {
							v22 = (v22)[:0]
						}
						for !in.IsDelim(']') {
							var v23 int
							v23 = int(in.Int())
							v22 = append(v22, v23)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.CustomWaitSecs)[key] = v22
					in.WantComma()
				}
				in.Delim('}')
			}
		case "connerrwaitsecs":
			if in.IsNull() {
				in.Skip()
				out.ConnErrWaitSecs = nil
			} else {
				in.Delim('[')
				if out.ConnErrWaitSecs == nil {
					if !in.IsDelim(']') {
						out.ConnErrWaitSecs = make([]int, 0, 8)
					} else {
						out.ConnErrWaitSecs = []int{}
					}
				} else {
					out.ConnErrWaitSecs = (out.ConnErrWaitSecs)[:0]
				}
				for !in.IsDelim(']') {
					var v24 int
					v24 = int(in.Int())
					out.ConnErrWaitSecs = append(out.ConnErrWaitSecs, v24)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ipsettings":
			if in.IsNull() {
				in.Skip()
				out.IPSettings = nil
			} else {
				if out.IPSettings == nil {
					out.IPSettings = new(IPSettings)
				}
				(*out.IPSettings).UnmarshalEasyJSON(in)
			}
		case "ipdomains":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.IPDomains = make(map[string]*IPDomains)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v25 *IPDomains
					if in.IsNull() {
						in.Skip()
						v25 = nil
					} else {
						if v25 == nil {
							v25 = new(IPDomains)
						}
						(*v25).UnmarshalEasyJSON(in)
					}
					(out.IPDomains)[key] = v25
					in.WantComma()
				}
				in.Delim('}')
			}
		case "transient":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Transient = make(map[string]bool)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v26 bool
					v26 = bool(in.Bool())
					(out.Transient)[key] = v26
					in.WantComma()
				}
				in.Delim('}')
			}
		case "ratedefer":
			out.RateDefer = bool(in.Bool())
		case "ratedefercheckmins":
			out.RateDeferCheckMins = int(in.Int())
		case "ratedefertarget":
			out.RateDeferTarget = int(in.Int())
		case "ratedeferwaitsecs":
			if in.IsNull() {
				in.Skip()
				out.RateDeferWaitSecs = nil
			} else {
				in.Delim('[')
				if out.RateDeferWaitSecs == nil {
					if !in.IsDelim(']') {
						out.RateDeferWaitSecs = make([]int, 0, 8)
					} else {
						out.RateDeferWaitSecs = []int{}
					}
				} else {
					out.RateDeferWaitSecs = (out.RateDeferWaitSecs)[:0]
				}
				for !in.IsDelim(']') {
					var v27 int
					v27 = int(in.Int())
					out.RateDeferWaitSecs = append(out.RateDeferWaitSecs, v27)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d751f33EncodeVelvetSender6(out *jwriter.Writer, in MTASettings) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"numconns\":"
		out.RawString(prefix[1:])
		out.Int(int(in.NumConns))
	}
	{
		const prefix string = ",\"customnumconns\":"
		out.RawString(prefix)
		if in.CustomNumConns == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v28First := true
			for v28Name, v28Value := range in.CustomNumConns {
				if v28First {
					v28First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v28Name))
				out.RawByte(':')
				out.Int(int(v28Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"retryfor\":"
		out.RawString(prefix)
		out.Int(int(in.RetryFor))
	}
	{
		const prefix string = ",\"sendsperconn\":"
		out.RawString(prefix)
		out.Int(int(in.SendsPerConn))
	}
	{
		const prefix string = ",\"deferwaitsecs\":"
		out.RawString(prefix)
		if in.DeferWaitSecs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v29, v30 := range in.DeferWaitSecs {
				if v29 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v30))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"customwaitsecs\":"
		out.RawString(prefix)
		if in.CustomWaitSecs == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v31First := true
			for v31Name, v31Value := range in.CustomWaitSecs {
				if v31First {
					v31First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v31Name))
				out.RawByte(':')
				if v31Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v32, v33 := range v31Value {
						if v32 > 0 {
							out.RawByte(',')
						}
						out.Int(int(v33))
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"connerrwaitsecs\":"
		out.RawString(prefix)
		if in.ConnErrWaitSecs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v34, v35 := range in.ConnErrWaitSecs {
				if v34 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v35))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ipsettings\":"
		out.RawString(prefix)
		if in.IPSettings == nil {
			out.RawString("null")
		} else {
			(*in.IPSettings).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"ipdomains\":"
		out.RawString(prefix)
		if in.IPDomains == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v36First := true
			for v36Name, v36Value := range in.IPDomains {
				if v36First {
					v36First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v36Name))
				out.RawByte(':')
				if v36Value == nil {
					out.RawString("null")
				} else {
					(*v36Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"transient\":"
		out.RawString(prefix)
		if in.Transient == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v37First := true
			for v37Name, v37Value := range in.Transient {
				if v37First {
					v37First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v37Name))
				out.RawByte(':')
				out.Bool(bool(v37Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"ratedefer\":"
		out.RawString(prefix)
		out.Bool(bool(in.RateDefer))
	}
	{
		const prefix string = ",\"ratedefercheckmins\":"
		out.RawString(prefix)
		out.Int(int(in.RateDeferCheckMins))
	}
	{
		const prefix string = ",\"ratedefertarget\":"
		out.RawString(prefix)
		out.Int(int(in.RateDeferTarget))
	}
	{
		const prefix string = ",\"ratedeferwaitsecs\":"
		out.RawString(prefix)
		if in.RateDeferWaitSecs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v38, v39 := range in.RateDeferWaitSecs {
				if v38 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v39))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MTASettings) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1d751f33EncodeVelvetSender6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MTASettings) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1d751f33EncodeVelvetSender6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MTASettings) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1d751f33DecodeVelvetSender6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MTASettings) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1d751f33DecodeVelvetSender6(l, v)
}
func easyjson1d751f33DecodeVelvetSender7(in *jlexer.Lexer, out *MTA) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "iplimits":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.IPLimits = make(map[string]*SendLimits)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v40 *SendLimits
					if in.IsNull() {
						in.Skip()
						v40 = nil
					} else {
						if v40 == nil {
							v40 = new(SendLimits)
						}
						(*v40).UnmarshalEasyJSON(in)
					}
					(out.IPLimits)[key] = v40
					in.WantComma()
				}
				in.Delim('}')
			}
		case "ippauses":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.IPPauses = make(map[string]bool)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v41 bool
					v41 = bool(in.Bool())
					(out.IPPauses)[key] = v41
					in.WantComma()
				}
				in.Delim('}')
			}
		case "settings":
			if in.IsNull() {
				in.Skip()
				out.Settings = nil
			} else {
				if out.Settings == nil {
					out.Settings = new(MTASettings)
				}
				(*out.Settings).UnmarshalEasyJSON(in)
			}
		case "trackingids":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.TrackingIDs = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v42 string
					v42 = string(in.String())
					(out.TrackingIDs)[key] = v42
					in.WantComma()
				}
				in.Delim('}')
			}
		case "sinktrackingids":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.SinkTrackingIDs = make(map[string]map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v43 map[string]string
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						v43 = make(map[string]string)
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v44 string
							v44 = string(in.String())
							(v43)[key] = v44
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.SinkTrackingIDs)[key] = v43
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d751f33EncodeVelvetSender7(out *jwriter.Writer, in MTA) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"iplimits\":"
		out.RawString(prefix[1:])
		if in.IPLimits == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v45First := true
			for v45Name, v45Value := range in.IPLimits {
				if v45First {
					v45First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v45Name))
				out.RawByte(':')
				if v45Value == nil {
					out.RawString("null")
				} else {
					(*v45Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"ippauses\":"
		out.RawString(prefix)
		if in.IPPauses == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v46First := true
			for v46Name, v46Value := range in.IPPauses {
				if v46First {
					v46First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v46Name))
				out.RawByte(':')
				out.Bool(bool(v46Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"settings\":"
		out.RawString(prefix)
		if in.Settings == nil {
			out.RawString("null")
		} else {
			(*in.Settings).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"trackingids\":"
		out.RawString(prefix)
		if in.TrackingIDs == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v47First := true
			for v47Name, v47Value := range in.TrackingIDs {
				if v47First {
					v47First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v47Name))
				out.RawByte(':')
				out.String(string(v47Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"sinktrackingids\":"
		out.RawString(prefix)
		if in.SinkTrackingIDs == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v48First := true
			for v48Name, v48Value := range in.SinkTrackingIDs {
				if v48First {
					v48First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v48Name))
				out.RawByte(':')
				if v48Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v49First := true
					for v49Name, v49Value := range v48Value {
						if v49First {
							v49First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v49Name))
						out.RawByte(':')
						out.String(string(v49Value))
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MTA) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1d751f33EncodeVelvetSender7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MTA) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1d751f33EncodeVelvetSender7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MTA) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1d751f33DecodeVelvetSender7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MTA) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1d751f33DecodeVelvetSender7(l, v)
}
func easyjson1d751f33DecodeVelvetSender8(in *jlexer.Lexer, out *IPSettings) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "allips":
			out.AllIPs = bool(in.Bool())
		case "iplist":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.IPList = make(map[string]*IPSetting)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v50 *IPSetting
					if in.IsNull() {
						in.Skip()
						v50 = nil
					} else {
						if v50 == nil {
							v50 = new(IPSetting)
						}
						(*v50).UnmarshalEasyJSON(in)
					}
					(out.IPList)[key] = v50
					in.WantComma()
				}
				in.Delim('}')
			}
		case "algorithm":
			out.Algorithm = string(in.String())
		case "captime":
			out.CapTime = string(in.String())
		case "sendcap":
			if in.IsNull() {
				in.Skip()
				out.SendCap = nil
			} else {
				if out.SendCap == nil {
					out.SendCap = new(int)
				}
				*out.SendCap = int(in.Int())
			}
		case "sendrate":
			if in.IsNull() {
				in.Skip()
				out.SendRate = nil
			} else {
				if out.SendRate == nil {
					out.SendRate = new(int)
				}
				*out.SendRate = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d751f33EncodeVelvetSender8(out *jwriter.Writer, in IPSettings) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"allips\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.AllIPs))
	}
	{
		const prefix string = ",\"iplist\":"
		out.RawString(prefix)
		if in.IPList == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v51First := true
			for v51Name, v51Value := range in.IPList {
				if v51First {
					v51First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v51Name))
				out.RawByte(':')
				if v51Value == nil {
					out.RawString("null")
				} else {
					(*v51Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"algorithm\":"
		out.RawString(prefix)
		out.String(string(in.Algorithm))
	}
	{
		const prefix string = ",\"captime\":"
		out.RawString(prefix)
		out.String(string(in.CapTime))
	}
	{
		const prefix string = ",\"sendcap\":"
		out.RawString(prefix)
		if in.SendCap == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.SendCap))
		}
	}
	{
		const prefix string = ",\"sendrate\":"
		out.RawString(prefix)
		if in.SendRate == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.SendRate))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IPSettings) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1d751f33EncodeVelvetSender8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IPSettings) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1d751f33EncodeVelvetSender8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IPSettings) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1d751f33DecodeVelvetSender8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IPSettings) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1d751f33DecodeVelvetSender8(l, v)
}
func easyjson1d751f33DecodeVelvetSender9(in *jlexer.Lexer, out *IPSetting) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "selected":
			out.Selected = bool(in.Bool())
		case "mintype":
			out.MinType = string(in.String())
		case "minpct":
			out.MinPct = int(in.Int())
		case "minnum":
			out.MinNum = int(in.Int())
		case "sendcap":
			if in.IsNull() {
				in.Skip()
				out.SendCap = nil
			} else {
				if out.SendCap == nil {
					out.SendCap = new(int)
				}
				*out.SendCap = int(in.Int())
			}
		case "sendrate":
			if in.IsNull() {
				in.Skip()
				out.SendRate = nil
			} else {
				if out.SendRate == nil {
					out.SendRate = new(int)
				}
				*out.SendRate = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d751f33EncodeVelvetSender9(out *jwriter.Writer, in IPSetting) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"selected\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Selected))
	}
	{
		const prefix string = ",\"mintype\":"
		out.RawString(prefix)
		out.String(string(in.MinType))
	}
	{
		const prefix string = ",\"minpct\":"
		out.RawString(prefix)
		out.Int(int(in.MinPct))
	}
	{
		const prefix string = ",\"minnum\":"
		out.RawString(prefix)
		out.Int(int(in.MinNum))
	}
	{
		const prefix string = ",\"sendcap\":"
		out.RawString(prefix)
		if in.SendCap == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.SendCap))
		}
	}
	{
		const prefix string = ",\"sendrate\":"
		out.RawString(prefix)
		if in.SendRate == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.SendRate))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IPSetting) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1d751f33EncodeVelvetSender9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IPSetting) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1d751f33EncodeVelvetSender9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IPSetting) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1d751f33DecodeVelvetSender9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IPSetting) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1d751f33DecodeVelvetSender9(l, v)
}
func easyjson1d751f33DecodeVelvetSender10(in *jlexer.Lexer, out *IPDomains) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "domain":
			out.Domain = string(in.String())
		case "linkdomain":
			out.LinkDomain = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d751f33EncodeVelvetSender10(out *jwriter.Writer, in IPDomains) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"linkdomain\":"
		out.RawString(prefix)
		out.String(string(in.LinkDomain))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IPDomains) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1d751f33EncodeVelvetSender10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IPDomains) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1d751f33EncodeVelvetSender10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IPDomains) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1d751f33DecodeVelvetSender10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IPDomains) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1d751f33DecodeVelvetSender10(l, v)
}
func easyjson1d751f33DecodeVelvetSender11(in *jlexer.Lexer, out *ConnKey) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "IP":
			out.IP = string(in.String())
		case "MXSuffix":
			out.MXSuffix = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d751f33EncodeVelvetSender11(out *jwriter.Writer, in ConnKey) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"IP\":"
		out.RawString(prefix[1:])
		out.String(string(in.IP))
	}
	{
		const prefix string = ",\"MXSuffix\":"
		out.RawString(prefix)
		out.String(string(in.MXSuffix))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ConnKey) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1d751f33EncodeVelvetSender11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ConnKey) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1d751f33EncodeVelvetSender11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ConnKey) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1d751f33DecodeVelvetSender11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ConnKey) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1d751f33DecodeVelvetSender11(l, v)
}
